apiVersion: v1
kind: Service
metadata:
  name: mateusz-socha-website-dev
spec:
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: mateusz-socha-website-dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mateusz-socha-website-dev
spec:
  selector:
    matchLabels:
      app: mateusz-socha-website-dev
  replicas: 1
  template:
    metadata:
      labels:
        app: mateusz-socha-website-dev
    spec:
      containers:
      - name: mateusz-socha-website-dev
        image: registry.gitlab.com/enlighten1/mateusz_socha-website:latest-development
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
      imagePullSecrets:
        - name: regcred
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: mateusz-socha-website-dev-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts: 
    - mateusz-socha-website-dev.enl-projects.com
    secretName: mateusz-socha-website-dev-tls
  rules:
  - host: mateusz-socha-website-dev.enl-projects.com
    http:
      paths:
      - backend:
          serviceName: mateusz-socha-website-dev
          servicePort: 80
